name: blog_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - codecov
  - pip
  - pip:
    - pelican[markdown]
    - ghp-import
    - pelican-render-math
# variables:
#   VAR1: valueA
#   VAR2: valueB
